# .github/workflows/deploy-node.yml
name: Deploy Node.js Application

on:
  push:
    branches:
      - project-*
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  detect-project:
    runs-on: ubuntu-latest
    outputs:
      project-name: ${{ steps.set-project.outputs.project-name }}
    
    steps:
    - name: Extract project name from branch
      id: set-project
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "project-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
  
  build-and-test:
    runs-on: ubuntu-latest
    needs: detect-project
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Test
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Zip artifact for deployment
      run: zip -r deployment.zip . -x "node_modules/*" "*.git*"
    
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: deployment.zip
  
  deploy:
    name: Deploy to Production
    needs: [detect-project, build-and-test]
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download deployment artifact
      uses: actions/download-artifact@v3
      with:
        name: node-app
    
    - name: Unzip deployment package
      run: unzip deployment.zip
    
    # Example deployment step for Heroku
    # (Replace this with your preferred deployment platform)
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ needs.detect-project.outputs.project-name }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}