# .github/workflows/deploy-static.yml
name: Deploy Static Site

on:
  push:
    branches:
      - project-*
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  detect-project:
    runs-on: ubuntu-latest
    outputs:
      project-name: ${{ steps.set-project.outputs.project-name }}
    
    steps:
    - name: Extract project name from branch
      id: set-project
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "project-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
  
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: detect-project
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    # Check for static site type
    - name: Determine deployment directory
      id: deploy-dir
      run: |
        if [ -d "dist" ]; then
          echo "deploy-directory=dist" >> $GITHUB_OUTPUT
        elif [ -d "build" ]; then
          echo "deploy-directory=build" >> $GITHUB_OUTPUT
        else
          echo "deploy-directory=." >> $GITHUB_OUTPUT
        fi
    
    # GitHub Pages deployment
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ steps.deploy-dir.outputs.deploy-directory }}
        repository-name: ${{ github.repository_owner }}/${{ needs.detect-project.outputs.project-name }}
        branch: gh-pages
        target-folder: /
        clean: true